### ISSUE TITLE
"Could not require ... (uninitialized constant ...)" with 2.0.0

### ISSUE THREAD

**Issue by kamenlitchev** [jarmo/require_all#26]
Hello,

I have a Cucumber project which uses require_all to, well, require some files in project subdirs. Since 2.0.0 whenever I try running the Cucumber tests (`cucumber features`), I get an error that:

> Could not require C:/no_such_file/app/model/bbb.rb (uninitialized constant Model::Ccc). Please require the necessary files (RequireAll::LoadError)

Full stacktrace is:

```
C:\no_such_file>cucumber features
Could not require C:/no_such_file/app/model/bbb.rb (uninitialized constant Model::Ccc). Please require the necessary files (RequireAll::LoadError)
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
C:/no_such_file/features/support/env.rb:3:in `<top (required)>'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load_code_file'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:147:in `load_file'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:88:in `block in load_files!'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `each'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `load_files!'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:270:in `load_step_definitions'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:67:in `run!'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
C:/Programs/Ruby_x64/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
C:/Programs/Ruby_x64/bin/cucumber:23:in `load'
C:/Programs/Ruby_x64/bin/cucumber:23:in `<main>'
```

Reverting to 1.5.0 solves the issue.

Environment is: Windows 10 x64, Ruby 2.5.0-2 x64 (Ruby installer). Project is newly set with "bundle install" and no gemfile.lock.

See attached file for a sample project: [no_such_file.zip](https://github.com/jarmo/require_all/files/1853130/no_such_file.zip). To reproduce, `bundle install` in the project directory then `cucumber features`

**Comment by jarmo** [comment]
Hi!

This is because PR #21, which is introduced in version 2.0.0. Basically require_all is now stricter to help preventing creation of hard-to-debug problems.

However, maybe a different error message would reveal its intent somehow better? Any suggestions?

**Comment by kamenlitchev** [comment]
Thanks for the quire reply!

Maybe print something that 2.0 changes the logic and each file will need to individually require dependencies

**Comment by jarmo** [comment]
Not each file, but only files, which dependencies have not been loaded before.

**Comment by DannyBen** [comment]
Bumped into a similar issue... this is a change for the worst, and sort of breaks the first statement of the README:

> Tired of futzing around with require statements everywhere, littering your code with require File.dirname(__FILE__) crap? 

Using `require_all` for years, never had any "hard to debug" issues... not sure why this change was introduced.

**Comment by jarmo** [comment]
Sorry for causing any troubles. The fact that you've not had any "hard to debug" issues might be that you've just become lucky (didn't write bad code and didn't use any dependencies with bad code). You can read more about the reasoning in PR #21 and PR #24.

**Comment by vveliev** [comment]
Hmmm ... I have base class

**Comment by enkessler** [comment]
@DannyBen @vveliev 

Before this change, the 'automagical' nature of this gem could lead to silent failures. It was 'invisibly dangerous'. After this change, failures will be loud, thus making the gem 'visibly safe'. The tradeoff was that the gem is no longer 'automagical' but merely 'automatic'.

Whereas before you could simply do something like

```
require_all 'my_models_folder'
```

now you will have to get any dependencies out of the way before trying to pull in everything else. So something more like

```
require 'my_models_folder/some_mix_in_used_all_over_the_place'
require 'my_models_folder/base_model'
require_all 'my_models_folder'
```

It's a couple extra steps but you can still load the bulk of your code all at once.

**Comment by DannyBen** [comment]
> Before this change, the 'automagical' nature of this gem could lead to silent failures

Well, I understand this rationale, and I understood it before. From an engineering perspective, I might even agree with you - if something causes too many issues, get rid of it instead of trying to fix its side effects.

However, this does not change how I feel about this change - as a user.

`require_all` without the magic is, for me, a sugar coated `Dir['*.rb'].each do { |f| require_relative f }`

I hate to be negative in this neighborhood, but for me, once this is gone, I stopped using `require_all` - it no longer fulfills my needs... sorry...

**Comment by enkessler** [comment]
I'll grant you that the 'catch and retry' magic was the big selling feature, yes. On the other hand, this is Ruby. Syntactic sugar coating and DSLs are pretty much the thing to do in the ecosystem. ;)

Seriously, though, we did try to think of a way to detect and automatically fix the partial loading problems (#8) problem but, unfortunately, we didn't come up with anything. There was also some discussion around having an option to run in the old 'unsafe' mode but...

> That's what I was pointing out - if anyone really, for some strange reasons, like to have strict mode off, then they can use an older version. I'm pretty sure that 100% of the users who would like to have it off, have not had to deal with any strange errors in production code thus far

...so that got nixed. Feel free to continue using versions in 1.x if they will still help your projects.

**Comment by jarmo** [comment]
Actually @DannyBen you *ironically* brought up a good point - since you do not need require_all anymore then it (hopefully) means that you also have one less dependency to worry about in your project. Having least amount of dependencies is always good in many ways even if it does not seem to be true in the first place ;)

However, if you have any ideas how to solve the initial problem, then don't hesitate to chime in!

And sorry if this change caused you any additional problems/work.

**Comment by DannyBen** [comment]
> then it (hopefully) means that you also have one less dependency to worry about 

Well... not exactly... I replaced it with [this one][1]...  :trollface: 


[1]: https://github.com/dannyben/requires

**Comment by DannyBen** [comment]
> Competition?! In the Open Source world? Scandalous!

heh :) - I think `require_all` is safe. I always thought it should be a part of Ruby (when it was still 'magical' that is), or that Ruby should at least support a simple `require 'some_directory'` to avoid all the `Dir['*'].each ... require` nonsense... this is one part of Ruby where the "make developers happy" concept failed me, and I found myself spending too much time worrying about requiring things... but maybe I am just looking for things to complain about...

Anyways - I hijacked enough of this thread, apologies, and thanks for the interesting discussion and for the insights into your decision making process. 

🎤 drop....

**Comment by enkessler** [comment]
Out of curiosity, what does your `requires` gem do that `require_all` does not? Aside from, I assume, put the magic back in.

If it has extra nice features, we could try to add them to `require_all` and have that `--strict` option after all (because not upgrading would no longer be a reasonable option due to wanting all of the other new stuff that we'd be adding).

**Comment by DannyBen** [comment]
Good question. In fact, I believe it does much less, since it is barely [16 lines of code][1].

What prompted me to make it was not lack of features on `require_all`'s part, but rather the desire for simplicity and control. I figured, if now `require_all` is (from my narrow standpoint) just a syntactic sugar around `Dir['*'].each ... require`, then why does it have to be longer than a few lines of code? 

The other reason is completely selfish - since I manage a few dozen Ruby gems and Rails projects, and the `require_all` change broke a lot of those, I figured I will use this opportunity to tidy up my dependency tree a bit, and gain more control over its features.


[1]: https://github.com/DannyBen/requires/blob/master/lib/requires.rb#L7
